# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yurahuchok
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: task-processor
# "service" is the name of this project. This will also be added to your AWS resource names.
service: task-processor

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
