# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yurahuchok
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: task-processor
# "service" is the name of this project. This will also be added to your AWS resource names.
service: task-processor

constructs:
  q-tasks:
    type: queue
    worker: consume
    batchSize: 10

plugins:
  - serverless-offline
  - serverless-lift

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  environment:
    QUEUE_URL: ${construct:q-tasks.queueUrl}

functions:
  health:
    handler: src/handler/health.handler
    events:
      - httpApi:
          path: /health
          method: get
  publish:
    handler: src/handler/publish.handler
    events:
      - httpApi:
          path: /publish
          method: post
  consume:
    handler: src/handler/consume.handler
